%
%   FILE NAME:
%       mainMethod.m
%
%   FILE PURPOSE:
%       To call the sub-functions to setup the components for a 
%       luminescent solar concentrator in order to call the Monte Carlo
%       ray-trace algorithm, simulating how photons interact with such a
%       device.
%-------------------------------------------------------------------------
function [lscCellEnergyBandgap, geometricGain, JscTotal_lscCell,        ...
    Voc_lscCell, FF_lscCell,JscTotal_bottomCell, Voc_bottomCell,        ...
    FF_bottomCell, powerEfficiency_module]                              ...
                                                                        ...
= mainMethod(lumPLFileIndex, lumAbsFileIndex, wgEdgeReflect,            ...
    wgEdgeScatter, topFilterBool, botFilterBool,lumPLQY,                ...
    lumOpticalDensity, lscCellThickness, lumScatterDistance,            ...
    wgSizeIndex, testDate, topFilterFileIndex,                          ...
    botFilterFileIndex, lscCellBifacialBool,                            ...
    lscCellEdgeLinedBool, lscCellNum, waveguideThickness,               ...
    waveguideRefIndex, percentNormal, botCellFileIndex, BlueFilterBool, ...
    BlueFilterIndex, fracIllumIndex, anisotropicBool,                   ...
    anisotropicFuncIndex, amolfAnisBool, amolfAnisFrac,                 ...
    detailedBalanceBool, lscCellFileIndex, ERE_lscCell,                 ...
    topFilterScalingR, filterRefFactor, topFilterScalingT,              ...
    filterTranFactor, iteration, numIterations, incidentLightType)
    
    %   Load all necessary data files:
    [reflect_lscCell, IQE_lscCell, reflect_bottomCell, IQE_bottomCell,  ...                              
        ...inputCellLength, inputCellThick,                             ...
        lumPLSpectrum, lumAbsSpectrum, reflectFilterTop,                ...
        transmitFilterTop, reflectFilterBottom,                         ...
        transmitFilterBottom, lumScattering, mirrorNameTop,             ...
        mirrorNameBottom, reflectBlueFilter, anisotropicFunc,           ...
        anisotropicFrac, lscCellEnergyBandgap,                          ...
        incidentLightSpectrumWatts, incidentLightSpectrumAmps,          ...
        incidentLightSpectrumWavelength]                                ...
                                                                        ...
    = dataLoading(lumPLFileIndex, lumAbsFileIndex, topFilterFileIndex,  ...
        botFilterFileIndex, botCellFileIndex, BlueFilterIndex,          ...
        anisotropicBool, anisotropicFuncIndex, amolfAnisBool,           ...
        amolfAnisFrac, detailedBalanceBool, lscCellFileIndex,           ...
        topFilterScalingR, filterRefFactor, topFilterScalingT,          ...
        filterTranFactor, incidentLightType);
    
    %   Display the run number and save file header string:
    [prefix]                                                            ...
                                                                        ...
    = parameterDisplay(lumPLFileIndex, topFilterBool, botFilterBool,    ...
        testDate, iteration, numIterations);
    
    %   Load all of the constants necessary to run this simulation:
    [wavelengthStep, simWavelengthRange, dataWavelengthRange,           ...
        photonStep, nAir, nGlass, nPolymer,                             ...
        wavelengthReference_450nmIndex, gridSize, spotSize,             ...
        fractionCellCovered, xInject, yInject, numXPoints, numYPoints,  ...
        numSimWavelength, xSize, ySize]                                 ...
                                                                        ...
     = constants(...inputCellLength,                                    ...
        wgSizeIndex, fracIllumIndex, waveguideRefIndex);
    
    %   Initialize the filter spectrum if applicable:
    [reflectFilterTop_pPol, transmitFilterTop_pPol,                     ...
        reflectFilterTop_sPol, transmitFilterTop_sPol,                  ...
        reflectFilterBottom_pPol, transmitFilterBottom_pPol,            ...
        reflectFilterBottom_sPol, transmitFilterBottom_sPol]            ...
                                                                        ...
    = initializeFilter(reflectFilterTop, transmitFilterTop,             ...
        reflectFilterBottom, transmitFilterBottom);
    
    %   Setup PL for luminophore:
    [lumPLSpectrumCompact] = initializeLuminophore(lumPLSpectrum);
    
    %   Set the scattering values for the polymer matrix and the glass
    %   layer:
    [probMatrixScatter, probGlassScatter]                               ...
                                                                        ...
    = initializeScattering(lumScattering, dataWavelengthRange,          ...
        lumScatterDistance, photonStep);
    
    %   Set the device geometry for the LSC:
    [geometry, plmaSize, solarCell, geometricGain, illuminationArea]    ...
                                                                        ...
    = initializeGeometry(spotSize, xSize, ySize, lscCellThickness,      ...
        ...inputCellThick, inputCellLength,                             ...
        gridSize, lscCellBifacialBool, waveguideThickness,              ...
        lscCellEdgeLinedBool, lscCellNum);
    
    %   Set the luminophore probability of a photon absorbed in waveguide:
    [probNotAbsPolymer]                                                 ...
                                                                        ...
    = luminophoreConcentration(waveguideThickness, lumAbsSpectrum,      ...
        wavelengthReference_450nmIndex, lumOpticalDensity,  ...
        photonStep);
    
    %   Set data structures for the monte carlo ray trace to export to:
    [collectPhotonOrigin_lscCell, collectPhotonWavelength_lscCell,      ...
        collectPhotonDir_lscCell, shortCircuitCurrent_lscCell,          ...
        collectPhotonOrigin_bottomCell,                                 ...
        collectPhotonWavelength_bottomCell, collectPhotonDir_bottomCell,...
        shortCircuitCurrent_bottomCell, incidentPower, numFilterBounces,...
        numLSCEdgeBounces, numWgModeBounces, numPLEvents,               ...
        numPhotonsLost]                                                 ...
                                                                        ...
    = initializeOutVar(numSimWavelength, numXPoints, numYPoints,        ...
        xInject, yInject);
    
    %   Run the monteCarlo method.  
    for wavelengthIndex = 1:numSimWavelength
        %   Start the clock for this specific iteration: 
        startTime = clock;  
        %   Call the monteCarlo function to simulate incident photons at
        %   the wavelengthIndex:
        [collectPhotonOrigin_lscCell(wavelengthIndex,:,:,:),            ...
            collectPhotonWavelength_lscCell(wavelengthIndex,:,:),       ...
            collectPhotonDir_lscCell(wavelengthIndex,:,:,:,:),          ...
            shortCircuitCurrent_lscCell(wavelengthIndex),               ...
            collectPhotonOrigin_bottomCell(wavelengthIndex,:,:,:),      ...
            collectPhotonWavelength_bottomCell(wavelengthIndex,:,:),    ...
            collectPhotonDir_bottomCell(wavelengthIndex,:,:,:,:),       ...
            shortCircuitCurrent_bottomCell(wavelengthIndex),            ...
            incidentPower(wavelengthIndex),                             ...
            numPhotonsLost(wavelengthIndex,:),                          ...
            numFilterBounces(wavelengthIndex,:,:),                      ...
            numPLEvents(wavelengthIndex,:,:),                           ...
            numLSCEdgeBounces(wavelengthIndex,:,:),                     ...
            numWgModeBounces(wavelengthIndex,:,:)]                      ...
                                                                        ...
        = monteCarlo(lumPLQY, solarCell, fractionCellCovered, xInject,  ...
            yInject, geometry, plmaSize, probMatrixScatter,             ...
            probGlassScatter, wavelengthIndex, wavelengthStep,          ...
            probNotAbsPolymer, photonStep, reflect_lscCell,             ...
            IQE_lscCell, reflect_bottomCell, IQE_bottomCell,            ...
            lumPLSpectrumCompact, nAir, nGlass,                         ...
            nPolymer, topFilterBool, botFilterBool,                     ...
            reflectFilterTop_sPol, transmitFilterTop_sPol,              ...
            reflectFilterTop_pPol, transmitFilterTop_pPol,              ...
            reflectFilterBottom_pPol, transmitFilterBottom_pPol,        ...
            reflectFilterBottom_sPol, transmitFilterBottom_sPol,        ...
            wgEdgeReflect, wgEdgeScatter, lscCellBifacialBool,          ...
            simWavelengthRange, dataWavelengthRange, gridSize,          ...
            percentNormal, BlueFilterBool, reflectBlueFilter,           ...
            anisotropicBool, amolfAnisBool, anisotropicFrac,            ...
            incidentLightSpectrumWatts, incidentLightSpectrumAmps,      ...
            incidentLightSpectrumWavelength, lscCellEdgeLinedBool,      ...
            lscCellNum);
        %   Stop the clock for this iteration and calculate the toal time:
        totalTime = clock - startTime;
        %   Save the total time taken for this iteration:
        timeSpent(wavelengthIndex) = 60*60*24*totalTime(3) +            ...
        60*60*totalTime(4) + 60*totalTime(5) + totalTime(6);
        %   Display the number of seconds taken to simulate this iteration:
        disp(strcat(num2str(simWavelengthRange(wavelengthIndex)),          ...
        ' nm light: ', num2str(timeSpent(wavelengthIndex)),             ...
        ' seconds to compute;'));
    end
    
    %   If using the detailed balance model:
    if detailedBalanceBool
        %   Calculate the figures of merit:
        [collectPhotonWavelength_lscCell,                               ...
            collectPhotonWavelength_bottomCell,                         ...
            collectPhotonRaw_lscCell, collectPhotonRaw_bottomCell,      ...
            IscTotal_lscCell, IscTotal_bottomCell, JscTotal_lscCell,    ...
            JscTotal_bottomCell, powerTotalIn, Voc_lscCell,             ...
            Voc_bottomCell, FF_lscCell, FF_bottomCell,                  ...
            powerTotalOut_lscCell, powerTotalOut_bottomCell,            ...
            powerTotalOut_module, powerEfficiency_module]               ...
                                                                        ...
        = outputVarCalc_detailedBalance(collectPhotonWavelength_lscCell,...
            collectPhotonWavelength_bottomCell,                         ...
            shortCircuitCurrent_lscCell, shortCircuitCurrent_bottomCell,...
            numSimWavelength, illuminationArea, incidentPower,          ...
            geometricGain, wavelengthStep, lscCellEnergyBandgap,        ...
            ERE_lscCell);
    else
        [collectPhotonWavelength_lscCell,                               ...
            collectPhotonWavelength_bottomCell,                         ...
            collectPhotonRaw_lscCell, collectPhotonRaw_bottomCell,      ...
            IscTotal_lscCell, IscTotal_bottomCell, JscTotal_lscCell,    ...
            JscTotal_bottomCell, powerTotalIn, Voc_lscCell,             ...
            Voc_bottomCell, FF_lscCell, FF_bottomCell,                  ...
            powerTotalOut_lscCell, powerTotalOut_bottomCell,            ...
            powerTotalOut_module, powerEfficiency_module]               ...
                                                                        ...
        = outputVarCalc(collectPhotonWavelength_lscCell,                ...
            collectPhotonWavelength_bottomCell,                         ...
            shortCircuitCurrent_lscCell, shortCircuitCurrent_bottomCell,...
            numSimWavelength, illuminationArea, incidentPower,          ...
            geometricGain, wavelengthStep);
    end
    
    %   Save the simulation data and workspace:
    saveFile(prefix,simWavelengthRange, dataWavelengthRange,            ...
        lscCellThickness, xSize, ySize, spotSize, lumPLSpectrum,        ...
        lumAbsSpectrum, lumOpticalDensity, lumPLQY,lumScatterDistance,  ...
        wgEdgeReflect, wgEdgeScatter, geometricGain,                    ...
        collectPhotonRaw_lscCell, collectPhotonRaw_bottomCell,          ...
        collectPhotonWavelength_lscCell, xInject, yInject,              ...
        collectPhotonWavelength_bottomCell, numPhotonsLost,             ...
        IscTotal_lscCell, IscTotal_bottomCell, testDate,                ...
        topFilterFileIndex, botFilterFileIndex, lscCellBifacialBool,    ...
        JscTotal_lscCell, Voc_lscCell, Voc_bottomCell, FF_lscCell,      ...
        FF_bottomCell, JscTotal_bottomCell, powerTotalOut_bottomCell,   ...
        powerTotalOut_lscCell, powerTotalOut_module, powerTotalIn,      ...
        powerEfficiency_module, collectPhotonDir_bottomCell,            ...
        collectPhotonDir_lscCell, numFilterBounces, numLSCEdgeBounces,  ...
        numWgModeBounces, waveguideThickness, mirrorNameTop,            ...
        mirrorNameBottom, numPLEvents, probNotAbsPolymer,               ...
        reflect_lscCell, reflect_bottomCell, IQE_lscCell,               ...
        IQE_bottomCell, lumPLSpectrumCompact, reflectFilterTop_sPol,    ...
        reflectFilterBottom_sPol, percentNormal, botCellFileIndex,      ...
        reflectBlueFilter, BlueFilterBool, anisotropicBool,             ...
        anisotropicFuncIndex, lscCellEnergyBandgap, filterRefFactor,    ...
        anisotropicFrac, ERE_lscCell, waveguideRefIndex, anisotropicFunc);
end
