%
%   FILE NAME:
%       monteCarloParameterTest.m
%
%   FILE DESCRIPTION:
%       This is just a dummy file used to automate the parameter check for
%       the C Code Conversion.
%
%-------------------------------------------------------------------------
function []                                                             ...
                                                                        ...
= monteCarloParameterTest()
    %   Define parameters:
    lumPLFileIndex = 4;
    lumAbsFileIndex = 4;
    wgEdgeReflect = 1;
    wgEdgeScatter = 0;
    topFilterBool = false;
    botFilterBool = false;
    lumPLQY = 1;
    lumOpticalDensity = 2;
    lscCellThickness = 10e-6;
    lumScatterDistance = 1e-1;
    wgSizeIndex = 10;
    testDate = 'test';
    topFilterFileIndex = 4;
    botFilterFileIndex = 4;
    lscCellBifacialBool = false;
    lscCellEdgeLinedBool = false;
    lscCellNum = 4;
    waveguideThickness = 100e-6;
    waveguideRefIndex = 1.44;
    percentNormal = 1;
    botCellFileIndex = 4;
    BlueFilterBool = false;
    BlueFilterIndex = 9;
    fracIllumIndex = 1;
    anisotropicBool = true;
    anisotropicFuncIndex = 5;
    amolfAnisBool = false;
    amolfAnisFrac = .25;
    detailedBalanceBool = false;
    lscCellFileIndex = 6;
    ERE_lscCell = .10;
    topFilterScalingR = false;
    filterRefFactor = 1;
    topFilterScalingT = false;
    filterTranFactor = 1;
    iteration = 1;
    numIterations = 1;
    incidentLightType = 'AM0';
    
    %   Load all necessary data files:
    [reflect_lscCell, IQE_lscCell, reflect_bottomCell, IQE_bottomCell,  ...                              
        ...inputCellLength, inputCellThick,                             ...
        lumPLSpectrum, lumAbsSpectrum, reflectFilterTop,                ...
        transmitFilterTop, reflectFilterBottom,                         ...
        transmitFilterBottom, lumScattering, mirrorNameTop,             ...
        mirrorNameBottom, reflectBlueFilter, anisotropicFunc,           ...
        anisotropicFrac, lscCellEnergyBandgap,                          ...
        incidentLightSpectrumWatts, incidentLightSpectrumAmps,          ...
        incidentLightSpectrumWavelength]                                ...
                                                                        ...
    = dataLoading(lumPLFileIndex, lumAbsFileIndex, topFilterFileIndex,  ...
        botFilterFileIndex, botCellFileIndex, BlueFilterIndex,          ...
        anisotropicBool, anisotropicFuncIndex, amolfAnisBool,           ...
        amolfAnisFrac, detailedBalanceBool, lscCellFileIndex,           ...
        topFilterScalingR, filterRefFactor, topFilterScalingT,          ...
        filterTranFactor, incidentLightType);
    
    %   Display the run number and save file header string:
    [prefix]                                                            ...
                                                                        ...
    = parameterDisplay(lumPLFileIndex, topFilterBool, botFilterBool,    ...
        testDate, iteration, numIterations);
    
    %   Load all of the constants necessary to run this simulation:
    [wavelengthStep, simWavelengthRange, dataWavelengthRange,           ...
        photonStep, nAir, nGlass, nPolymer,                             ...
        wavelengthReference_450nmIndex, gridSize, spotSize,             ...
        fractionCellCovered, xInject, yInject, numXPoints, numYPoints,  ...
        numSimWavelength, xSize, ySize]                                 ...
                                                                        ...
     = constants(...inputCellLength,                                    ...
        wgSizeIndex, fracIllumIndex, waveguideRefIndex);
    
    %   Initialize the filter spectrum if applicable:
    [reflectFilterTop_pPol, transmitFilterTop_pPol,                     ...
        reflectFilterTop_sPol, transmitFilterTop_sPol,                  ...
        reflectFilterBottom_pPol, transmitFilterBottom_pPol,            ...
        reflectFilterBottom_sPol, transmitFilterBottom_sPol]            ...
                                                                        ...
    = initializeFilter(reflectFilterTop, transmitFilterTop,             ...
        reflectFilterBottom, transmitFilterBottom);
    
    %   Setup PL for luminophore:
    [lumPLSpectrumCompact] = initializeLuminophore(lumPLSpectrum);
    
    %   Set the scattering values for the polymer matrix and the glass
    %   layer:
    [probMatrixScatter, probGlassScatter]                               ...
                                                                        ...
    = initializeScattering(lumScattering, dataWavelengthRange,          ...
        lumScatterDistance, photonStep);
    
    %   Set the device geometry for the LSC:
    [geometry, waveguideEdges, plmaSize, solarCell, geometricGain,      ...
        illuminationArea]                                               ...
                                                                        ...
    = initializeGeometry(spotSize, xSize, ySize, lscCellThickness,      ...
        ...inputCellThick, inputCellLength,                             ...
        gridSize, lscCellBifacialBool, waveguideThickness,              ...
        lscCellEdgeLinedBool, lscCellNum);
    
    %   Set the luminophore probability of a photon absorbed in waveguide:
    [probNotAbsPolymer]                                                 ...
                                                                        ...
    = luminophoreConcentration(waveguideThickness, lumAbsSpectrum,      ...
        wavelengthReference_450nmIndex, lumOpticalDensity,  ...
        photonStep);
    
    %   Set data structures for the monte carlo ray trace to export to:
    [collectPhotonOrigin_lscCell, collectPhotonWavelength_lscCell,      ...
        collectPhotonDir_lscCell, shortCircuitCurrent_lscCell,          ...
        collectPhotonOrigin_bottomCell,                                 ...
        collectPhotonWavelength_bottomCell, collectPhotonDir_bottomCell,...
        shortCircuitCurrent_bottomCell, incidentPower, numFilterBounces,...
        numLSCEdgeBounces, numWgModeBounces, numWgEdgeBounces,          ...
        numPLEvents, numPhotonsLost]                                    ...
                                                                        ...
    = initializeOutVar(numSimWavelength, numXPoints, numYPoints,        ...
        xInject, yInject);
    
    %   Run the monteCarlo method.  
    wavelengthIndex = 1;
        %   Call the monteCarlo function to simulate incident photons at
        %   the wavelengthIndex:
        [collectPhotonOrigin_lscCell(wavelengthIndex,:,:,:),            ...
            collectPhotonWavelength_lscCell(wavelengthIndex,:,:),       ...
            collectPhotonDir_lscCell(wavelengthIndex,:,:,:,:),          ...
            shortCircuitCurrent_lscCell(wavelengthIndex),               ...
            collectPhotonOrigin_bottomCell(wavelengthIndex,:,:,:),      ...
            collectPhotonWavelength_bottomCell(wavelengthIndex,:,:),    ...
            collectPhotonDir_bottomCell(wavelengthIndex,:,:,:,:),       ...
            shortCircuitCurrent_bottomCell(wavelengthIndex),            ...
            incidentPower(wavelengthIndex),                             ...
            numPhotonsLost(wavelengthIndex,:),                          ...
            numFilterBounces(wavelengthIndex,:,:),                      ...
            numPLEvents(wavelengthIndex,:,:),                           ...
            numLSCEdgeBounces(wavelengthIndex,:,:),                     ...
            numWgModeBounces(wavelengthIndex,:,:),                      ...
            numWgEdgeBounces(wavelengthIndex,:,:)]                      ...
                                                                        ...
        = monteCarlo(lumPLQY, solarCell, fractionCellCovered, xInject,  ...
            yInject, geometry, waveguideEdges, plmaSize,                ...
            probMatrixScatter, probGlassScatter, wavelengthIndex,       ...
            wavelengthStep, probNotAbsPolymer, photonStep,              ...
            reflect_lscCell, IQE_lscCell, reflect_bottomCell,           ...
            IQE_bottomCell, lumPLSpectrumCompact, nAir, nGlass,         ...
            nPolymer, topFilterBool, botFilterBool,                     ...
            reflectFilterTop_sPol, transmitFilterTop_sPol,              ...
            reflectFilterTop_pPol, transmitFilterTop_pPol,              ...
            reflectFilterBottom_pPol, transmitFilterBottom_pPol,        ...
            reflectFilterBottom_sPol, transmitFilterBottom_sPol,        ...
            wgEdgeReflect, wgEdgeScatter, lscCellBifacialBool,          ...
            simWavelengthRange, dataWavelengthRange, gridSize,          ...
            percentNormal, BlueFilterBool, reflectBlueFilter,           ...
            anisotropicBool, amolfAnisBool, anisotropicFrac,            ...
            incidentLightSpectrumWatts, incidentLightSpectrumAmps,      ...
            incidentLightSpectrumWavelength);
end
                                       
                                
                                
                                
                                
                                